### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by ZeeK4163** [mvanlobensels/random-track-generator#3]
When I try to run the program, it gives me the following error in the line 84 of "track_generator.py":
```
vor.filtered_regions = np.array(vor.regions)[vor.point_region[:vor.npoints//5]]
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (301,) + inhomogeneous part.
```
I can't figure out how to solve the problem as I haven't changed the code

**Comment by mvanlobensels** [comment]
This should have been fixed now. Please install the specific package versions according to the requirements.txt
